[http]
address="0.0.0.0"

#[sonarr.main]
#address="http://localhost:8989"
#apikey="c2cba97d97184fe282ca91b22d528189"


#[quickwit]
#address="http://192.168.10.4:7280"
#index="homers"
#wait_for=true

#
#[tautulli]
#address="http://localhost:9191"
#apikey="404ddd4cb0924f57bd2533d106c8e377"

#[jellyfin.main]
#address="https://jellyfin.mcth.fr"
#apikey="4e9856d0b8a04444bb6b1ff1ad8bf838"

[radarr.main]
address="http://localhost:7878/"
apikey="9122f767ae754e0f90804f2432e7c56f"
#
#[plex.kevin]
#address="http://localhost:32400"
#token="UsZFM65uenR17FzAC9j6"
#
#[overseerr]
#address="http://localhost:5055"
#apikey="MTY1ODY2MTYzMzcyNWRiMDEwMTUxLThkZWItNGVkNy05YzQ3LWJlNDliYTczMWQxYyk="
#requests=1000
#[overseerr]
#address="http://localhost:5055"
#apikey="MTczMzUwMDE0NDM0NDZhZjBlYzdkLTA5MmMtNGUyNC05ZmQxLTU5NDA3Y2ZmMWJhMw=="
#requests=1000
[readarr.main]
address="http://localhost:8787"
apikey="46743a957b3e40f5be7ead69764309b5"
